CREATE TABLE ADRESS
(
  ID_ADRESS INT NOT NULL,
  KRAJ INT NOT NULL,
  MIEJSCOWOŚĆ INT NOT NULL,
  ULICA INT NOT NULL,
  MIESZKANIE INT NOT NULL,
  KOD_POCZTOWY INT NOT NULL,
  PRIMARY KEY (ID_ADRESS)
);

CREATE TABLE OSOBA
(
  ID_OSOBA INT NOT NULL,
  IMIE INT NOT NULL,
  NAZWISKO INT NOT NULL,
  PESEL INT NOT NULL,
  DATA_URODZENIA INT NOT NULL,
  TELEFON INT NOT NULL,
  EMAIL INT NOT NULL,
  PRIMARY KEY (ID_OSOBA)
);

CREATE TABLE DANE_LOGOWANIA
(
  ID_LOGOWANIA INT NOT NULL,
  LOGIN INT NOT NULL,
  HASLO INT NOT NULL,
  PRIMARY KEY (ID_LOGOWANIA)
);

CREATE TABLE 
(
);

CREATE TABLE AUTOR
(
  ID_AUTORA INT NOT NULL,
  IMIE VARCHAR(11) NOT NULL,
  NAZWISKO VARCHAR(11) NOT NULL,
  DATA_URODZENIA DATE NOT NULL,
  ID_ADRESS INT NOT NULL,
  PRIMARY KEY (ID_AUTORA),
  FOREIGN KEY (ID_ADRESS) REFERENCES ADRESS(ID_ADRESS)
);

CREATE TABLE WYDAWNICZTWO
(
  ID_WYDAWNICTWA INT NOT NULL,
  NAZWA_WYDAWNICTWA VARCHAR(20) NOT NULL,
  ID_ADRESS INT NOT NULL,
  PRIMARY KEY (ID_WYDAWNICTWA),
  FOREIGN KEY (ID_ADRESS) REFERENCES ADRESS(ID_ADRESS)
);

CREATE TABLE CZYTELNIK
(
  ID_CZYTELNIKA INT NOT NULL,
  WYDZIAL VARCHAR NOT NULL,
  KIERUNEK VARCHAR NOT NULL,
  STATUS VARCHAR NOT NULL,
  MAX_ILOSC INT NOT NULL,
  ID_ADRESS INT NOT NULL,
  ID_OSOBA INT NOT NULL,
  ID_LOGOWANIA INT NOT NULL,
  PRIMARY KEY (ID_CZYTELNIKA),
  FOREIGN KEY (ID_ADRESS) REFERENCES ADRESS(ID_ADRESS),
  FOREIGN KEY (ID_OSOBA) REFERENCES OSOBA(ID_OSOBA),
  FOREIGN KEY (ID_LOGOWANIA) REFERENCES DANE_LOGOWANIA(ID_LOGOWANIA)
);

CREATE TABLE FILIA
(
  ID_FILIA INT NOT NULL,
  WYDZIAL VARCHAR NOT NULL,
  NAZWA VARCHAR NOT NULL,
  ID_ADRESS INT NOT NULL,
  PRIMARY KEY (ID_FILIA),
  FOREIGN KEY (ID_ADRESS) REFERENCES ADRESS(ID_ADRESS)
);

CREATE TABLE KSIAZKA
(
  ID_KSIAZKI INT NOT NULL,
  TYTUL VARCHAR(20) NOT NULL,
  ROK_WYDANIA INT NOT NULL,
  MIEJSCE_WYDANIA VARCHAR(20) NOT NULL,
  GATUNEK VARCHAR NOT NULL,
  OPIS VARCHAR NOT NULL,
  CENA FLOAT NOT NULL,
  ISBN INT NOT NULL,
  LICZBA INT NOT NULL,
  ILOSC_STRON INT NOT NULL,
  ID_AUTORA INT NOT NULL,
  ID_WYDAWNICTWA INT NOT NULL,
  PRIMARY KEY (ID_KSIAZKI),
  FOREIGN KEY (ID_AUTORA) REFERENCES AUTOR(ID_AUTORA),
  FOREIGN KEY (ID_WYDAWNICTWA) REFERENCES WYDAWNICZTWO(ID_WYDAWNICTWA)
);

CREATE TABLE PRACOWNIK
(
  ID_PRACOWNIKA INT NOT NULL,
  STANOWISKO INT NOT NULL,
  WYNOGRODZENIA FLOAT NOT NULL,
  ID_FILIA INT NOT NULL,
  ID_OSOBA INT NOT NULL,
  ID_ADRESS INT NOT NULL,
  ID_LOGOWANIA INT NOT NULL,
  PRIMARY KEY (ID_PRACOWNIKA),
  FOREIGN KEY (ID_FILIA) REFERENCES FILIA(ID_FILIA),
  FOREIGN KEY (ID_OSOBA) REFERENCES OSOBA(ID_OSOBA),
  FOREIGN KEY (ID_ADRESS) REFERENCES ADRESS(ID_ADRESS),
  FOREIGN KEY (ID_LOGOWANIA) REFERENCES DANE_LOGOWANIA(ID_LOGOWANIA)
);

CREATE TABLE EGZEMPLARZ
(
  ID_EKZEMPLARZA INT NOT NULL,
  ID_KSIAZKI INT NOT NULL,
  PRIMARY KEY (ID_EKZEMPLARZA),
  FOREIGN KEY (ID_KSIAZKI) REFERENCES KSIAZKA(ID_KSIAZKI)
);

CREATE TABLE WYPOZYCENIA
(
  ID_WYPOZYCENIA INT NOT NULL,
  DATA_WYPORZYCZENIA DATE NOT NULL,
  DATA_ODDANIA DATE NOT NULL,
  STATUS VARCHAR NOT NULL,
  KWOTA_KARY INT NOT NULL,
  ID_CZYTELNIKA INT NOT NULL,
  ID_PRACOWNIKA INT NOT NULL,
  ID_EKZEMPLARZA INT NOT NULL,
  ID_FILIA INT NOT NULL,
  PRIMARY KEY (ID_WYPOZYCENIA),
  FOREIGN KEY (ID_CZYTELNIKA) REFERENCES CZYTELNIK(ID_CZYTELNIKA),
  FOREIGN KEY (ID_PRACOWNIKA) REFERENCES PRACOWNIK(ID_PRACOWNIKA),
  FOREIGN KEY (ID_EKZEMPLARZA) REFERENCES EGZEMPLARZ(ID_EKZEMPLARZA),
  FOREIGN KEY (ID_FILIA) REFERENCES FILIA(ID_FILIA)
);